FROM python:3.11.1

# # Install Node.js
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

# # Install Python
# # RUN apt-get install -y python3 python3-pip
RUN apt update && apt install -y python3 python3-pip

