# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY ./server/usersManager/requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY ./server/usersManager .

# Set environment variables, if necessary
# ENV VARIABLE_NAME=value

# Expose the port on which the Flask app will run
EXPOSE 5000

# Set the command to run the Flask application
CMD ["python", "app.py"]
